---
- name: Check if Zerotier is already present.
  command: which zerotier-cli
  failed_when: false
  changed_when: false
  check_mode: false
  register: zerotier_command_result

- name: Download Zerotier install convenience script.
  get_url:
    url: https://install.zerotier.com
    dest: /tmp/get-zerotier.sh
    mode: 0775
  when: zerotier_command_result.rc == 1

- name: Run Zerotier install convenience script.
  command: /tmp/get-zerotier.sh
  environment:
    CHANNEL: stable
  when: zerotier_command_result.rc == 1

- block:
    - name: Start zerotier-one service
      service:
        name: zerotier-one
        state: started
      when:
        - zerotier_command_result.rc == 1
      notify:
        - enable zerotier-one

    - name: create facts.d
      file:
        path: /etc/ansible/facts.d
        recurse: true
        state: directory
      when:
        - zerotier_command_result.rc == 1

    - name: Install zerotier custom facts
      copy:
        src: zerotier.fact.py
        dest: /etc/ansible/facts.d/zerotier.fact
        mode: 0755
      when:
        - zerotier_command_result.rc == 1

    - name: Re-gather facts
      setup: ~
      when:
        - zerotier_command_result.rc == 1

  when:
    - zerotier_repo is not defined or zerotier_repo is succeeded
    - not ansible_check_mode
  tags:
    - installation
    - packages
